### ISSUE TITLE
Post/Essay about visualization options for showing an emerging ecosystem

### ISSUE THREAD

**Issue by rufuspollock** [life-itself/secondrenaissance#184]
When "shaping" visualization of an emerging ecosystem I want to do research/analysis on existing visualization approaches for analogous problems/domains so that we learn from and take inspiration from them (plus we can start sharing about the idea even if we haven't finalized approach in our area)

Inspiration is from ...

See #4 for original efforts in this domain.

## Acceptance

NB: can start with a discussion thread in the forum and then turn this into a blog post. advantage is we work "in the open" and can get comments

- [ ] Where are we and what is our intention (see notes in Analysis section below)
- [ ] Examples of visualizations (cf notes below)
- [ ] Analysis of those with pros/cons for our situation (wireframing ideas?)
- [ ] Summary / conclusion with any recommendations ...

## Tasks

- [ ] Collect examples here or in a discussion on forum
- [ ] Refine
- [ ] Write up ...
  - [ ] Include relevant material from notes below
- [ ] Add a link to this discussion thread and/or blog post in an appropriate place on this page https://ecosystem.lifeitself.org/sensemaking 

### Where are we and what is our intention

Current intention of this phase of ecosystem mapping: provide more/better ways to understand this ecosystem and its relation to broader social change ecosystem. This work could take many forms e.g.
- Visualizations 
- Written analysis
- Collecting novel data e.g. text collection to do topic analysis or concept clustering

Comment: ultimately probably two needs:
- a marketing need for one compelling visualization ("looks cool" or "conveys an essential point"). Something that might attract attention and engagement in the project.
- broader analysis (visual or not) to identify interesting aspects of this
  - e.g. a "State of Sensemaking" report, something like State of JS (https://stateofjs.com/en-US)
    - N.B. We did a "State of Sensemaking" Ecosystem Summary report in 2020: https://docs.google.com/document/d/1ryeEOcmxaMzlZRZ-ZFXNMp6VUoML4IofETkEYwdkQBo/edit#heading=h.ttxb831vocov

Qs from Matt:
- What is the openness to do different things? **Very open to whatever delivers sensemaking**
  - How much do you want to develop on top of phase I vs figuring it out newly ... **Ans: we are very open to new**
- What is timeline of project? **At least ~20d for Matt. Though can be less and possibly more.**

### Examples of visualisations

- Past research https://github.com/life-itself/ecosystem/issues/4 
- Current list of related efforts: https://ecosystem.lifeitself.org/related-efforts
- Here's a crude "map" of sub-tribes that got traction: https://twitter.com/rufuspollock/status/1501160815277318146
- a simple effort to collect language and visuals (ie. images/screenshots) could be a simple start, e.g. do a wordcloud or topicmaps ...
- There are various options for the "nodes" of a visual map, e.g.
  - "map" of concepts
  - "map" of orgs 
- https://twitter.com/exgenesis/status/1562059107233894402/photo/1
- https://ich.unesco.org/dive/constellation/

**Comment by catherinet1** [comment]
Updated this issue with notes organised by heading (and corresponding to Acceptance criteria) to support the write-up of our meeting brainstorming

**Comment by rufuspollock** [comment]
@mattosborn next steps is to add links with screenshot, brief commentary etc to this issue.

**Comment by elisapaka** [comment]
FIXED. Post in discussion thread: https://github.com/orgs/life-itself/discussions/1043
