### ISSUE TITLE
Overview of names/synonyms work

### ISSUE THREAD

**Issue by elisapaka** [life-itself/secondrenaissance#251]
What purpose does this serve?

- First item of a rosetta stone piece: allows people to map / connect between these different versions / subtribes
  - in this form being wiki-like, rough is fine
  - in more polished form it is a lead-in piece from ecosystem section
  - ... and even more polished it becomes 👇
- Publication in its own right: a literature survey so that people can reference and refer to it ...

**Appetite:** 1d writing + 1d integrating feedback and publishing

## Acceptance

- [ ] Published as wiki page **2024-04-05 ❌ Have published under `/publications`: https://secondrenaissance.net/publications/overview-ecosystem-names**
- [ ] Published as blog post **2024-04-05 ❌ As per above**
- [ ] Blog post shared on research collective chat, GitHub and twitter
- [ ] BONUS: if there are glossary items you identify and start to write up (e.g. "metacrisis")

*What does a publishable version look like?*

- [x] 'High' thoroughness sections for:
  - [x] Second Renaissance
  - [x] Metamodern
  - [x] Metacrisis
  - [x] Integral
- [x] 'Medium' thoroughness sections for:
  - [x] Polycrisis
  - [x] Regerenative movement
  - [x] Liminal Web
  - [x] Game B 
  - [x] Great Turning
- [x] 'Low' thoroughness sections for:
  - [x] Ecological civilisation
  - [x] [Emergentsia](https://www.whatisemerging.com/opinions/the-rise-of-the-emergentsia-meaning-making-in-a-time-between-worlds)
  - [x] [Sensemaking Web](https://medium.com/rebel-wisdom/a-story-to-bind-us-the-intellectual-deep-web-and-a-new-grand-narrative-9b32e36857c3)
  - [ ] Wisdom Age **2024-04-05 ❌ Won't include this due to appetite constraints and since it seems significantly broader than 2R**
  - [x] Teal
  - [x] Holomovement
- [x] Strong introduction setting out the context and linking to ecosystem mapping

*What does each level of 'thoroughness' involve?*
- All levels include:
  - Origin / history
  - Definition / explanation
  - How the term is used in the context of the ecosystem / by whom (ideally with quote)
  - Links to further readings / resources (if applicable)
- Specifically for each level:
  - High: 2-3 paragraphs + screenshots + key claims / debates (if applicable)
  - Medium: 1-2 paragraphs + screenshots
  - Low: 1-2 sentences

## Tasks

- [x] Add screenshots to high and medium sections
- [x] Add further content to high and medium sections
- [x] Add further readings / resources to all sections
- [x] Create new (low thoroughness) sections
- [x] Remove paragraph on reasons for 2R name (save for a separate post) **2024-04-04 Stubbed a page in the 'wiki' folder for the essay on reasons for 2R naming – have saved the paragraph there: https://github.com/life-itself/ecosystem/blob/main/content/wiki/second-renaissance-name.md**
- [x] Edit introduction to reflect changes
- [x] Fix numberings for references
- [x] Get feedback from research collective
  - [x] Share as gdoc that people can comment on **2024-04-03 ✅ Shared link to wiki post and asked feedback on the 'metamodern' section as a sample**
  - [x] Review & integrate feedback **2024-04-05 ✅ Incorporated feedback from Simon**
  - [x] Incorporate Rufus feedback (see below)
- [x] Publish 
  - [x] As wiki page **see acceptance**
  - [ ] As blog post
- [ ] Share the blog post
  - [ ] On research community chat
  - [ ] On GitHub
  - [ ] On twitter

## Inbox 

- Polymodernity
- Meta Tribe - https://twitter.com/TylerAlterman/status/1305265874157395976, and https://www.youtube.com/watch?v=4aXvHBIoF0A
- Anthropocene? 
- Twelve Tribes of Transformation - https://www.whatisemerging.com/opinions/twelve-tribes-of-transformation-awakening-the-active-ingredients-of-a-new-civilisation
- [Intellectual Deep Web - https://medium.com/rebel-wisdom/a-story-to-bind-us-the-intellectual-deep-web-and-a-new-grand-narrative-9b32e36857c3
- Rich Bartlett's Metamodernism 101 - https://twitter.com/RichDecibels/status/1294300519847034880

## FAQs

- Will we be publishing this as a blog post? (in addition to the wiki page) **Yes**
- Liminal Web and GameB - high or medium thoroughness?
  - Liminal Web is used a lot so on that basis could be 'high', but not a very 'meaty' concept so not much to say on it ... **Medium; explain why 'Liminal' (and what it means) + 'Web'**
  - GameB there is lots more to say and many people make reference to it, but it feels like more of a distinct thing / project within the ecosystem, than a real synonym / term for the wider space **Ok in medium for now**
- Introduction: is there a particular ecosystem page that we'll want this post to be connected to / setting out the context for? **✅2024-04-02 YES, /ecosystem/ page ...**
- General feedback: what do you think about the levels of thoroughness I've set out & the terms I've allocated to each? **✅2024-04-03 seems good**
- Add Anthropocene to "low"? **Can we find any example of the use of the term in the more specific sense for this movement/ecosystem ...**
  - https://theconversation.com/the-anthropocene-already-exists-in-our-heads-even-if-its-now-officially-not-a-geological-epoch-226554 "even in their official rejection, the International Union of Geological Scientists noted the Anthropocene as a concept is part of popular culture, as evidenced by the museum exhibition but also various artworks and books.The extent to which the Anthropocene really exists depends on our recognition and acceptance of the golden thread that we are all in an active back and forth relationship with the Earth. A socio-ecological relationship that has and will continue to shape our human-environment past, present and future." + i see people mobilising this concept in e.g. arts+culture to galvanise response to climate emergency etc. def broader than 2R but seems to me related enough to add as "low"

Next step: write out metamodern (good enough)

## Rufus feedback

- 👏 great job. especially in framing
  - [x] Need a better title - let's gemini it **Going with "Many Names, One Ecosystem?: Deciphering the Different Terms for the Second Renaissance Movement"**
  - [x] Minor: is there another metacrisis video for schmactenberger other than green pill one?
  - [x] To myself - Delete: "of the Western world"
  - [x] Need more "further reading" on second renaissance point e.g. let's link to Varela. also cite anything on "time between worlds" (e.g. Zak Stein), also Sylvie florence performance ...
- Meta/process points
  - ❓ Create zotero collection for each case for further resources?
  - [ ] Can we use footnotes **Would these go at the bottom of the page, or at the bottom of each section? The former would be quite cumbersome to update, especially if we will be adding more content over time** **💬2024-04-10 markdown supports footnotes out of the box like so `^[1]` with definition wherever you want** **❌ 2024-04-17 WONTFIX. This doesn't seem to work**
- ⏭️ Let's publish and distribute ...
  - [x] Where do we publish? 2r.net/articles/ or li.org? e.g. `/articles/` or `/reports/` (shouldn't be in wiki) **put in 'publications' page - published here: https://secondrenaissance.net/publications/overview-ecosystem-names**

**Comment by catherinet1** [comment]
I added a couple of links I found from the introduction of this essay - https://lifeitself.org/blog/2021/12/09/mapping-for-emergence - where we mentioned some alternative names for the ecosystem, one for Sensemaking Web and one for Emergentsia. Also added Intellectual Deep Web and corresponding link to the Inbox.

**Comment by catherinet1** [comment]
P.s. 1) we could tweet a link to this post in response to this tweet: https://twitter.com/positive_loop/status/1775855027308937310
2) the thread contains pointers to resources on what is metamodernism, most notably richard bartlett 'metamodernism 101' thread

**Comment by catherinet1** [comment]
@elisapaka  Google Doc with comments/feedback is here: https://docs.google.com/document/d/1fkyqlepLCtokdjD_6Lqmy-7kF6Z2s6H7_MhRfWmXLUY/edit

**Comment by elisapaka** [comment]
@rufuspollock I think this is now in a place where it could be shared more widely (Catherine read it this morning and gave some good feedback, which I've incorporated). I wasn't clear where we got to on Friday as to whether we should publish it as a blog post, or hold off until we've decided what we want to do with it given the new strategy for the 2R site and forum etc.

**Comment by elisapaka** [comment]
FIXED. Essay is complete and has been published on the 2r.net site under `/publications`: https://secondrenaissance.net/publications/overview-ecosystem-names
