### ISSUE TITLE
Recruitment for user research interviews

### ISSUE THREAD

**Issue by catherinet1** [life-itself/secondrenaissance#264]
## Acceptance

- [x] 5 people have booked a slot for user research interviews **5 interviews scheduled: Simon and Alexandre on Thursday 11th, Lisa and Bene on Friday 12th, Cassius on Monday 15th**
  - [ ] Nice to have: 10 people

## Tasks

- [x] Draft message **See Elisa message in Hub group chat**
- [x] Set up scheduling link **Link to schedule a 40-min timeslot on 11th, 12th, or 15th April: https://cal.com/ctran/40min**
- [x] Send invitation to  
  - [x] Hub group chat **2024-04-04 Elisa sent and asked at dinner**
  - [x] Get Involved chat **2024-04-05 Catherine sent and follow-up on 2024-04-09**
  - [x] General LI chat **2024-04-05 Catherine sent and follow-up on 2024-04-09**
  - [ ] Personal contacts we would like to invite
    - [ ] e.g. previous hub residents
    - [ ] e.g. some people outside of LI bubble
- [x] Schedule appointments with these people

## Issue tree

- How many people do we want to recruit? **:key: 5-10 people**
- Who are we targeting? What kind of (mix of) people?
- What is the request? **40-min user research interview...** 
- When do we want to do the user research interviews? **:key: Ideally end of next week, so that we can review and integrate feedback at the beginning of the next week**
- Do we want to offer test users something in return?
- Where are the materials from 2022 user research interviews? **:key: Recordings and notes here: https://drive.google.com/drive/folders/1l2Hex2Vasfqrwli5U9K30hZcWSWPW0wb**
- What do we want from these interviews? **Gut reactions, rather than advice/suggestions/trying to be helpful"**
- What specific questions are we seeking responses to? What do we want to know/find out?

## Interviewees

- Simon - research community
- Alexandre, Lisa, Bene - currently at Hub
- Cassius - in Get Involved WhatsApp group chat

**Comment by catherinet1** [comment]
FIXED. 5 interviews scheduled: Simon and Alexandre on Thursday 11th, Lisa and Bene on Friday 12th, Cassius on Monday 15th. 

Also sent a second message with "last call" for participants in Get Involved and General Whatsapp group chats today so someone else may yet sign up.

**Comment by catherinet1** [comment]
A couple more people signed up so now we have 7 interviews scheduled.
